# Generated by Django 5.0.3 on 2024-03-28 15:49

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_play_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.models.play_image_file_path
            ),
        ),
    ]
